import LegalLayout from './LegalLayout'

const EFFECTIVE = '31 May 2026'
const ENTITY    = 'AI Squadron (operated by Prathick Manivannan, an individual / sole proprietor)'
const EMAIL     = 'legal@ai-squadron.com'
const SUPPORT   = 'support@ai-squadron.com'

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service" effective={EFFECTIVE}>

      <Section title="1. Parties and Acceptance">
        <p>
          These Terms of Service ("Terms") constitute a legally binding agreement between you ("User", "Customer", or "you")
          and <strong>{ENTITY}</strong> ("AI Squadron", "we", "us", or "our"), governing your access to and use of the
          AI Squadron platform, software, APIs, websites, and any products or services derived therefrom (collectively,
          the "Services").
        </p>
        <p>
          By accessing, registering for, or using the Services — including subscribing to any paid plan or purchasing a
          product — you confirm that you have read, understood, and agree to be bound by these Terms in their entirety.
          <strong> If you do not agree, you must not access or use the Services.</strong>
        </p>
        <p>
          If you are accepting on behalf of an organisation, you represent and warrant that you have the authority to bind
          that organisation, and "you" refers to that organisation.
        </p>
      </Section>

      <Section title="2. Nature of the Services">
        <p>
          AI Squadron is an autonomous venture orchestration platform that employs artificial intelligence agents to
          research market niches, generate software products ("SaaS ventures"), create media content ("media channels"),
          and automate associated business operations.
        </p>
        <p>
          You acknowledge and agree that:
        </p>
        <ul>
          <li>Products and content generated by AI agents are algorithmic outputs and may contain errors, inaccuracies, or omissions.</li>
          <li>AI Squadron does not guarantee that any generated product will achieve commercial viability, generate revenue, or meet any specific performance metric.</li>
          <li>AI-generated content must be reviewed by you before public distribution, and you bear full responsibility for any content published through accounts you own or control.</li>
          <li>The platform is provided for informational and entrepreneurial exploration purposes. Nothing in the Services constitutes legal, financial, medical, or tax advice.</li>
        </ul>
      </Section>

      <Section title="3. Accounts and Eligibility">
        <p>
          To access paid or advanced features, you must register for an account. You agree to:
        </p>
        <ul>
          <li>Provide accurate, complete, and current registration information at all times.</li>
          <li>Maintain the security of your password and accept all risks of unauthorised access to your account.</li>
          <li>Notify us immediately at <a href={`mailto:${SUPPORT}`}>{SUPPORT}</a> if you suspect any unauthorised use.</li>
          <li>Be at least 18 years of age, or the age of majority in your jurisdiction if higher.</li>
          <li>Not create accounts on behalf of third parties without their express written consent.</li>
        </ul>
        <p>
          We reserve the right to suspend or terminate accounts that violate these Terms, engage in fraudulent activity,
          or whose use we determine, in our sole discretion, is harmful to us or other users.
        </p>
      </Section>

      <Section title="4. Payment, Billing and Subscriptions">
        <p>
          All financial transactions are processed by <strong>Paddle.com Market Limited ("Paddle")</strong>, our designated
          payment processor. When you purchase a subscription or product, your contract for payment is with Paddle, not
          AI Squadron directly. Paddle's terms of service and privacy policy govern the payment transaction.
        </p>
        <p>
          By subscribing to a paid plan, you authorise Paddle to charge your designated payment method on a recurring
          basis at the applicable subscription interval (monthly or annual) until you cancel.
        </p>
        <p>
          Prices are quoted in United States Dollars (USD) and are exclusive of any applicable taxes. As Merchant of
          Record, Paddle collects and remits all applicable taxes (VAT, GST, sales tax) on your behalf.
        </p>
        <p>
          We reserve the right to modify pricing at any time with at least 14 days' notice. Continued use of the Services
          after a price change constitutes acceptance of the new pricing.
        </p>
        <p>
          Subscription fees are non-refundable except as expressly stated in our Refund Policy.
        </p>
      </Section>

      <Section title="5. Acceptable Use Policy">
        <p>You agree that you will not use the Services to:</p>
        <ul>
          <li>Violate any applicable law, regulation, court order, or governmental directive, including but not limited to the Information Technology Act, 2000 (India) and applicable international law.</li>
          <li>Generate, distribute, or publish content that is defamatory, obscene, harassing, hateful, discriminatory, or otherwise unlawful.</li>
          <li>Infringe the intellectual property rights of any third party, including copyright, trademark, or patent.</li>
          <li>Engage in spam, phishing, or any deceptive or misleading commercial practices.</li>
          <li>Attempt to reverse-engineer, decompile, or derive source code from any component of the Services.</li>
          <li>Use automated scraping tools against our platform beyond what is expressly permitted by our API documentation.</li>
          <li>Interfere with or disrupt the integrity or performance of the Services or the data of other users.</li>
          <li>Circumvent any access controls, usage limits, or security features of the platform.</li>
          <li>Create or operate ventures that engage in pyramid schemes, multi-level marketing, gambling, or other activities prohibited by applicable law.</li>
        </ul>
        <p>
          We may investigate suspected violations and cooperate with law enforcement authorities. We reserve the right to
          remove any content, suspend any account, or report any conduct to relevant authorities at our sole discretion.
        </p>
      </Section>

      <Section title="6. Intellectual Property">
        <Subsection title="6.1 Our IP">
          The AI Squadron platform, including all software, algorithms, designs, workflows, agent architectures, documentation,
          trademarks, and trade secrets, are the exclusive property of AI Squadron and are protected by applicable
          intellectual property laws.
        </Subsection>
        <Subsection title="6.2 Your Content">
          You retain ownership of any original content, data, or materials you upload to the platform ("Your Content").
          You grant AI Squadron a non-exclusive, worldwide, royalty-free licence to use, process, and display Your Content
          solely for the purpose of providing the Services to you.
        </Subsection>
        <Subsection title="6.3 AI-Generated Output">
          Subject to your compliance with these Terms and payment of applicable fees, AI Squadron assigns to you all right,
          title, and interest in and to the specific software code, text, and media assets generated by the platform
          specifically for your account ("Generated Output"). You may use, modify, distribute, and commercialise the
          Generated Output without restriction.
        </Subsection>
        <Subsection title="6.4 Feedback">
          Any feedback, suggestions, or ideas you provide regarding the Services may be used by AI Squadron freely and
          without obligation or compensation to you.
        </Subsection>
      </Section>

      <Section title="7. Disclaimer of Warranties">
        <p>
          THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT ANY WARRANTY OF ANY KIND, EXPRESS OR
          IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, AI SQUADRON DISCLAIMS ALL WARRANTIES, INCLUDING
          BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, TITLE,
          ACCURACY, AND ANY WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.
        </p>
        <p>
          AI Squadron does not warrant that: (a) the Services will be uninterrupted, error-free, or secure; (b) any
          Generated Output will be accurate, complete, or fit for any particular purpose; (c) any venture generated by
          the platform will be profitable or commercially viable; or (d) the platform will comply with the specific
          terms of service of any third-party platform (including YouTube, TikTok, Railway, or Stripe).
        </p>
      </Section>

      <Section title="8. Limitation of Liability">
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL AI SQUADRON, ITS OPERATORS, AFFILIATES,
          OFFICERS, EMPLOYEES, AGENTS, SUPPLIERS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
          CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, REVENUE, DATA,
          BUSINESS OPPORTUNITIES, GOODWILL, OR ANTICIPATED SAVINGS, EVEN IF AI SQUADRON HAS BEEN ADVISED OF THE
          POSSIBILITY OF SUCH DAMAGES.
        </p>
        <p>
          THE AGGREGATE LIABILITY OF AI SQUADRON FOR ALL CLAIMS RELATING TO THE SERVICES IN ANY CALENDAR YEAR WILL NOT
          EXCEED THE GREATER OF: (a) THE TOTAL FEES PAID BY YOU TO AI SQUADRON IN THE THREE (3) MONTHS IMMEDIATELY
          PRECEDING THE EVENT GIVING RISE TO THE CLAIM; OR (b) ONE HUNDRED US DOLLARS (USD $100).
        </p>
        <p>
          Some jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages.
          In such jurisdictions, our liability is limited to the maximum extent permitted by law.
        </p>
      </Section>

      <Section title="9. Indemnification">
        <p>
          You agree to indemnify, defend, and hold harmless AI Squadron and its operators, affiliates, officers,
          employees, and agents from and against any claims, liabilities, damages, losses, costs, and expenses
          (including reasonable legal fees) arising out of or relating to:
        </p>
        <ul>
          <li>Your use of the Services in violation of these Terms.</li>
          <li>Your Content or Generated Output that you deploy or distribute publicly.</li>
          <li>Your violation of any third-party rights, including intellectual property or privacy rights.</li>
          <li>Any products or services you offer to end-users using Generated Output from the platform.</li>
          <li>Any dispute between you and a third party, including your customers or business partners.</li>
        </ul>
      </Section>

      <Section title="10. Third-Party Services and Integrations">
        <p>
          The Services integrate with various third-party APIs and services, including but not limited to Supabase,
          Anthropic, Google, OpenRouter, ElevenLabs, Railway, Paddle, YouTube, and TikTok (collectively, "Third-Party
          Services"). Your use of Third-Party Services is governed solely by those providers' terms and policies.
        </p>
        <p>
          AI Squadron is not responsible for the availability, accuracy, reliability, or terms of any Third-Party Service.
          You are solely responsible for ensuring your use of Third-Party Services complies with their respective
          terms of service.
        </p>
        <p>
          AI Squadron makes no guarantee that any Generated Output will pass the moderation policies or content guidelines
          of any Third-Party Service. You bear full responsibility for any content you publish to third-party platforms.
        </p>
      </Section>

      <Section title="11. Termination">
        <p>
          You may terminate your account at any time by contacting us at <a href={`mailto:${SUPPORT}`}>{SUPPORT}</a>.
          Termination does not entitle you to any refund except as provided in our Refund Policy.
        </p>
        <p>
          We reserve the right to suspend or terminate your account immediately, without notice or liability, if:
        </p>
        <ul>
          <li>You materially breach these Terms and fail to cure such breach within 7 days of written notice.</li>
          <li>We are required to do so by law or government order.</li>
          <li>Your use of the Services creates a risk of harm to us, other users, or the public.</li>
          <li>Continued provision of the Services to you is no longer commercially feasible.</li>
        </ul>
        <p>
          Upon termination, Sections 6, 7, 8, 9, 12, and 13 survive and remain in full force and effect.
        </p>
      </Section>

      <Section title="12. Governing Law and Dispute Resolution">
        <p>
          These Terms are governed by and construed in accordance with the laws of the Republic of India, without regard
          to conflict of law principles. The parties expressly submit to the exclusive jurisdiction of the courts located
          in Chennai, Tamil Nadu, India for the resolution of any disputes arising under or in connection with these Terms.
        </p>
        <p>
          Before initiating any formal proceeding, the parties agree to attempt good-faith resolution through direct
          negotiation for a period of 30 days. Disputes that cannot be resolved through negotiation shall be submitted
          to binding arbitration under the Arbitration and Conciliation Act, 1996 (India), with a single arbitrator
          seated in Chennai, and conducted in English.
        </p>
        <p>
          Users located outside India acknowledge that local consumer protection laws may provide additional rights.
          Nothing in these Terms is intended to limit any non-waivable rights under applicable local law.
        </p>
      </Section>

      <Section title="13. General Provisions">
        <ul>
          <li><strong>Entire Agreement.</strong> These Terms, together with our Privacy Policy and Refund Policy, constitute the entire agreement between you and AI Squadron regarding the Services.</li>
          <li><strong>Severability.</strong> If any provision of these Terms is found invalid or unenforceable, the remaining provisions continue in full force.</li>
          <li><strong>Waiver.</strong> Failure to enforce any provision of these Terms does not constitute a waiver of our right to enforce it in the future.</li>
          <li><strong>Assignment.</strong> You may not assign your rights or obligations under these Terms without our written consent. We may assign our rights to any successor in interest.</li>
          <li><strong>Modifications.</strong> We may update these Terms at any time. We will provide at least 14 days' notice for material changes. Continued use of the Services after the effective date constitutes acceptance.</li>
          <li><strong>Force Majeure.</strong> AI Squadron is not liable for delays or failures caused by events beyond our reasonable control, including acts of God, governmental actions, pandemics, or internet infrastructure failures.</li>
          <li><strong>No Partnership.</strong> Nothing in these Terms creates a partnership, joint venture, employment, or agency relationship between you and AI Squadron.</li>
        </ul>
      </Section>

      <Section title="Contact">
        <p>
          For questions about these Terms, contact us at:{' '}
          <a href={`mailto:${EMAIL}`} style={{ color: '#7c3aed' }}>{EMAIL}</a>
        </p>
      </Section>

    </LegalLayout>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 40 }}>
      <h2 style={{ fontSize: 20, fontWeight: 700, color: '#e2e8f0', marginBottom: 14, borderBottom: '1px solid #1e1e3a', paddingBottom: 10 }}>
        {title}
      </h2>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12, color: '#94a3b8', fontSize: 14, lineHeight: 1.8 }}>
        {children}
      </div>
    </section>
  )
}

function Subsection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <strong style={{ color: '#cbd5e1' }}>{title} </strong>
      {children}
    </div>
  )
}
